version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    allow:
      - dependency-name: github.com/stimtech/*
    reviewers:
      - "stimtech/team-brown"
    pull-request-branch-name:
      separator: "-"
