version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - "stimtech/team-brown"
    pull-request-branch-name:
      separator: "-"

