
version: '3'
services:
  mysql:
    container_name: mig-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mig
      MYSQL_USER: mig
      MYSQL_PASSWORD: mig
      MYSQL_DATABASE: mig
    command: |
      mysqld --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./test.ignore/sql:/docker-entrypoint-initdb.d
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  postgres:
    container_name: mig-postgres
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mig
      POSTGRES_PASSWORD: mig
      POSTGRES_DB: mig