# This workflow is generated and will be automatically synchronized.
# Source: https://github.com/stimtech/terraform-github/blob/main/provider/workflows/pipeline-library-go.yml

name: Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go-analyze:
    name: Analyze Go
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check out action
        uses: actions/checkout@v3
        with:
          repository: stimtech/action-go-analyze
          ref: 2.0.0
          path: ./.github/actions/go-analyze
          token: ${{ secrets.GH_PAT }}

      - name: Analyze Go
        uses: ./.github/actions/go-analyze
        with:
          codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  pipeline-complete:
    needs: go-analyze
    if: always()
    name: Pipeline Complete
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          STATUS=$(echo '${{ toJSON(needs) }}' | jq '[.[] | select(.result!="success")] | length')
          exit $STATUS
